### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Tiago-Anastacio** [devrimgunduz/passwordcheck_cracklib#1]
Thank you for that package.

I have a question not directly related to this one( and I know th's not the correct list :)

It is about the package pldebugger. For postgreSQL 10 releases you provide it on the community repository.
But I can't find it in repo for postgreSQL 11 ?

Thank you very much.

**Comment by devrimgunduz** [comment]
Please use pgsql-pkg-yum@lists.postgresql.org for such questions.

Regards, Devrim
