### ISSUE TITLE
Wrong CRACKLIB_DICTPATH for passswordcheck_cracklib_11 on CentOS 7

### ISSUE THREAD

**Issue by branecc** [devrimgunduz/passwordcheck_cracklib#2]
Great job.
But when I installed passwordcheck_cracklib on CentOS 7 with command:
# yum install passswordcheck_cracklib_11
and tried to change password, I got the following errors in postgres log:
...
/usr/lib/cracklib_dict.pwd.gz: No such file or directory
2022-09-06 10:57:04.743 UTC [9334] ERROR:  password is easily cracked
2022-09-06 10:57:04.743 UTC [9334] DETAIL:  cracklib diagnostic: error loading dictionary
...
Looked at Makefile:
...
# uncomment the following two lines to enable cracklib support
PG_CPPFLAGS = -DUSE_CRACKLIB '-DCRACKLIB_DICTPATH="/usr/lib/cracklib_dict"'
SHLIB_LINK = -lcrack
...

But on CentOS 7, CRACKLIB_DICTPATH path should be:

# uncomment the following two lines to enable cracklib support
PG_CPPFLAGS = -DUSE_CRACKLIB '-DCRACKLIB_DICTPATH="/usr/share/cracklib/pw_dict"'
SHLIB_LINK = -lcrack

as seen from
# rpm -ql cracklib-dicts
/usr/lib64/cracklib_dict.hwm
/usr/lib64/cracklib_dict.pwd
/usr/lib64/cracklib_dict.pwi
/usr/sbin/mkdict
/usr/sbin/packer
/usr/share/cracklib/cracklib-small.hwm
/usr/share/cracklib/cracklib-small.pwd
/usr/share/cracklib/cracklib-small.pwi
/usr/share/cracklib/pw_dict.hwm
/usr/share/cracklib/pw_dict.pwd
/usr/share/cracklib/pw_dict.pwi

**Comment by devrimgunduz** [comment]
Hi,

Fixed in 2.0.1. Thanks for the report!
